```{r}
# /*===========================================================
#' # Preparation
# /*===========================================================

# === Packages ===#
library(sp)
library(spdep)
library(spatialreg)
library(sf)
library(raster)
library(data.table)
library(tidyverse)
library(dplyr)
library(magrittr)
library(gstat)
library(GWmodel)
library(scam)
library(parallel)
library(magic)
library(stringr)
library(ggplot2)
library(tictoc)
library(here)

# === Set working directory ===#
setwd(here())

# === load functions ===#
#* source all the functions in the Functions folder
fs::dir_ls(here("R"), full.names = TRUE) %>%
  lapply(., function(x) source(x))
```

```{r}
# /*===========================================================
#' # Create a field
# /*===========================================================
# ! Define field and plot characteristics here
sim_data <-
  gen_fields(
    plot_length = 12, # the length of a plot (in number of cells)
    plot_width = 3, # the width of a plot (in number of cells)
    cell_buffer = 1,
    aunit_length = 2, # the length of an analysis unit (in number of cells)
    aunit_width = 3, # the width of an analysis unit (in number of cells)
    cell = 6, # the length of a cell in meter
    #* how wide the field is
    # field_col = c(36, 72, 144), # the number of cell columns
    field_col = 144, # the number of cell columns
    #* how tall the field is
    field_row = 72 # the number of row columns
  ) %>%
  #--- add trial design layout ---#
  assign_trial_design(., design = c("Latin Square Fixed 5", "Latin Square Fixed 6")) %>%
  #--- generate true field parameters ---#
  mutate(field_pars = list(
    gen_field_parameters(
      field_sf,
      sp_range = 600,
      gstat_model = "Sph",
      nsim = 2
    )
  )) %>%
  #--- generate trial design ---#
  mutate(trial_design = list(
    gen_trial_design(field_sf, field_pars, design_name, num_treatments)
  )) %>%
  #--- generate regression data ---#
  mutate(reg_data = list(
    gen_analysis_data(field_pars, field_sf, field_au_sf, trial_design)
  )) %>%
  #--- create the weight matrix if necessary ---#
  mutate(weight_matrix = list(
    gen_weight_matrix(reg_data, cutoff = 50)
  ))
```

```{r}
save_reg_data_sep <- function(data_file_path, keep_meta_only = FALSE) {
  unnested_data <-
    readRDS(data_file_path) %>%
    unnest(reg_data) %>%
    data.table()

  lapply(
    1:nrow(unnested_data),
    function(x) {
      saveRDS(
        unnested_data[x, ],
        paste0("Shared/Data/SimData/sim_data_", x, ".rds")
      )
    }
  )
}
```

# Sanity check

```{r}
i <- 2
trial_design <- sim_data$trial_design[[i]] %>% .[sim == 1, ]
field_sf <- sim_data$field_sf[[i]] %>% data.table()

td_sf <-
  trial_design[field_sf, on = c("block_id", "plot_in_block_id")] %>%
  st_as_sf()

ggplot(data = td_sf) +
  geom_sf(aes(fill = factor(N_tgt))) +
  scale_fill_viridis_d()
```