#' Delineate plot and treatment blocks on a field
#'
#' Delineate plot and treatment blocks on a field. The plot and block ids are added as columns to field_sf of the data generated by gen_fields()
#'
#' @param field_data data.frame (object generated by gen_fields())
#' @param design character (design name)
#' @returns data.frame
#' @import data.table
#' @export
assign_trial_design <- function(field_data, design = "Latin Square Fixed 5") {
  field_with_design <-
    field_data %>%
    dplyr::rowwise() %>%
    #--- add the layout for all the designs ---#
    # this adds cols_plot_in_block and rows_plot_in_block, which are used to impose
    # the trial designs on the field
    dplyr::mutate(design_layout = list(
      add_design_layout(plot_length, field_col)
    )) %>%
    dplyr::select(-plot_length) %>%
    tidyr::unnest(cols = "design_layout") %>%
    #--- keep only the used-specified designs ---#
    dplyr::filter(design_name %in% design) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(plot_block_id_data = list(
      gen_plot_block_ids(
        field_sf = field_sf,
        plot_length = plot_length,
        plot_width = plot_width,
        cols_plot_in_block = cols_plot_in_block,
        rows_plot_in_block = rows_plot_in_block,
        cell_buffer = cell_buffer
      )
    )) %>%
    #--- add trial design layout to field_sf ---#
    dplyr::mutate(field_sf = list(
      dplyr::left_join(field_sf, plot_block_id_data, by = "cell_id")
    )) %>%
    dplyr::select(-plot_block_id_data)

  return(field_with_design)
}

#' Create plot and block ids based on the design layout
#'
#' Create plot and block ids based on the design. Used internally.
#'
#' @param field_sf data.frame (object generated by gen_fields())
#' @param plot_length numeric
#' @param plot_width numeric
#' @param cols_plot_in_block numeric
#' @param rows_plot_in_block numeric
#' @param cell_buffer numeric
#' @returns data.frame
#' @import data.table
gen_plot_block_ids <- function(field_sf, plot_length, plot_width, cols_plot_in_block, rows_plot_in_block, cell_buffer) {
  cols_cell_in_block <- plot_length * cols_plot_in_block
  rows_cell_in_block <- plot_width * rows_plot_in_block

  # === plot and block ids ===#
  plot_block_id_data <-
    data.table(field_sf) %>%
    # === plot id ===#
    .[, plot_row_id := ceiling(row_id / plot_width)] %>%
    .[, plot_col_id := ceiling(col_id / plot_length)] %>%
    .[, plot_id := plot_col_id + (plot_row_id - 1) * max(plot_col_id)] %>%
    # === buffer zone in each plot ===#
    .[, buffer := as.numeric(col_id <= min(col_id) + cell_buffer - 1 |
      col_id >= max(col_id) - cell_buffer + 1),
    by = plot_id
    ] %>%
    # === block id ===#
    .[, block_row_id := ceiling(row_id / rows_cell_in_block)] %>%
    .[, block_col_id := ceiling(col_id / cols_cell_in_block)] %>%
    .[, block_id := block_col_id + (block_row_id - 1) * max(block_col_id)] %>%
    # === plot id within a block (for assigning N rates) ===#
    .[order(block_id, plot_id, cell_id), ] %>%
    .[, plot_within_row_id := plot_row_id -
      floor(plot_row_id / rows_plot_in_block) * rows_plot_in_block] %>%
    .[, plot_within_col_id := plot_col_id -
      floor(plot_col_id / cols_plot_in_block) * cols_plot_in_block] %>%
    .[plot_within_row_id == 0, plot_within_row_id := rows_plot_in_block] %>%
    .[plot_within_col_id == 0, plot_within_col_id := cols_plot_in_block] %>%
    .[, plot_in_block_id := plot_within_col_id +
      (plot_within_row_id - 1) * cols_plot_in_block] %>%
    data.table() %>%
    .[, .(cell_id, buffer, plot_id, block_id, plot_in_block_id, plot_row_id, plot_col_id)]

  return(plot_block_id_data)
}

#' Specify design layout
#'
#' Specify design layout
#'
#' @param plot_length numeric
#' @param field_col numeric
#' @returns data.frame
#' @import data.table
add_design_layout <- function(plot_length, field_col) {
  design_layout_table <-
    dplyr::tribble(
      ~design_name, ~plot_length, ~cols_plot_in_block, ~rows_plot_in_block, ~num_treatments,
      "Latin Square Fixed 5", plot_length, 5, 5, 5,
      "Latin Square Fixed 6", plot_length, 6, 6, 6,
      "Latin Square Random", plot_length, 6, 6, 6,
      "Latin Square Cascade", plot_length, 6, 6, 6,
      "Alternate Block", plot_length, 3, 6, 6,
      "Checkerboard", plot_length, 2, 3, 6,
      "Randomized Block", plot_length, 2, 3, 6,
      "Completely Random", plot_length, 1, 1, 6,
      "Fixed Strip Grad", field_col, 1, 12, 6,
      "Fixed Strip Fluc 1", field_col, 1, 6, 6,
      "Fixed Strip Fluc 2", field_col, 1, 6, 6,
      "Random Strip", field_col, 1, 6, 6,
      "Cascade Plot", plot_length, 12, 12, 6
    ) %>%
    data.table()

  return(design_layout_table)
}
